const projectsData = [
    {
        "title": "EMSI Learn — LMS",
        "description": "A comprehensive Learning Management System designed for EMSI. It features multi-role dashboards for students, teachers, and admins, enabling seamless course management, secure file sharing, and real-time grade tracking.",
        "features": ["Multi-role Authentication", "Course Content Management", "Interactive Gradebook", "Secure File Storage", "Real-time Notifications"],
        "icon": "fas fa-graduation-cap",
        "image": "", 
        "isNew": true,
        "isFeatured": true,
        "gradient": "linear-gradient(135deg, #0ea5e9 0%, #7c3aed 100%)",
        "badges": ["Django", "Python", "MySQL", "Tailwind CSS"],
        "github": "https://github.com/anass-fs/EMSI-LEARN",
        "demo": ""
    },
    {
        "title": "NextGen - DevConnect",
        "description": "A professional social networking platform tailored for developers. Built with Django 5, it facilitates project collaboration, real-time messaging, and community building through shared stories and technical insights.",
        "features": ["Project Collaboration", "Real-time Messaging", "Developer Profiles", "Social Feed"],
        "icon": "fas fa-users",
        "image": "", 
        "isNew": true,
        "isFeatured": false,
        "gradient": "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
        "badges": ["Django 5", "Python", "MySQL", "Railway"],
        "github": "https://github.com/anass-fs/nextgen",
        "demo": "https://nextgen-app.up.railway.app/"
    },
    {
        "title": "E-commerce Admin System",
        "description": "A robust backoffice solution for managing online stores. This platform provides deep insights into inventory, order processing, and customer management using a scalable Spring Boot architecture.",
        "features": ["Inventory Tracking", "Order Lifecycle", "Sales Analytics", "Customer CRM"],
        "icon": "fas fa-shopping-cart",
        "image": "",
        "isNew": false,
        "isFeatured": true,
        "gradient": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        "badges": ["Spring Boot", "Java", "MySQL", "Thymeleaf"],
        "github": "https://github.com/anass-fs/project-java-backoffice",
        "demo": "https://anass-fs.github.io/project-java-backoffice/"
    },
    {
        "title": "SantéPlus - Healthcare Platform",
        "description": "An integrated medical appointment booking system. Designed to bridge the gap between patients and healthcare providers with an intuitive scheduling interface and patient record management.",
        "features": ["Online Appointment Booking", "Patient Record System", "Provider Scheduling"],
        "icon": "fas fa-hospital",
        "image": "",
        "isNew": false,
        "isFeatured": false,
        "gradient": "linear-gradient(135deg, #11998e 0%, #38ef7d 100%)",
        "badges": ["PHP", "Symfony", "MySQL", "MVC"],
        "github": "https://github.com/anass-fs/project-php",
        "demo": "https://docs.google.com/videos/d/1zn97QIxbnnKvkvBvUarKXZ4GrEl1XNOECjG_jIx6Q28/edit?usp=drive_link"
    },
    {
        "title": "Hotel Management System",
        "description": "A high-performance console application for hotel operations. Implements advanced data structures and algorithms in C to manage reservations, billing, and room availability with precision.",
        "features": ["Reservation Management", "Automated Billing", "Room Tracking", "Data Persistence"],
        "icon": "fas fa-hotel",
        "image": "",
        "isNew": false,
        "isFeatured": false,
        "gradient": "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
        "badges": ["C Language", "Algorithms", "File I/O"],
        "github": "https://github.com/anass-fs/hotel-reservation-c",
        "demo": ""
    },
    {
        "title": "TechStore Back-Office",
        "description": "A complete backoffice web application for managing an online store. Built entirely with modern front-end technologies, featuring inventory management, order tracking, and sales analytics dashboards.",
        "features": ["Inventory Management", "Order Processing", "Sales Dashboard", "Customer Management"],
        "icon": "fas fa-store",
        "image": "",
        "isNew": false,
        "isFeatured": false,
        "gradient": "linear-gradient(135deg, #ff6a3d 0%, #ffd166 100%)",
        "badges": ["HTML5", "CSS3", "JavaScript ES6+"],
        "github": "https://github.com/anass-fs",
        "demo": ""
    },
    {
        "title": "Professional Portfolio",
        "description": "My personal portfolio website, optimized for performance and accessibility. Built with a focus on modern UI/UX principles and semantic HTML to showcase my journey as a software engineer.",
        "features": ["Responsive Design", "Dark/Light Mode", "Dynamic Content", "SEO Optimization"],
        "icon": "fas fa-code",
        "image": "",
        "isNew": false,
        "isFeatured": false,
        "gradient": "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
        "badges": ["HTML5", "CSS3", "JavaScript"],
        "github": "https://github.com/anass-fs",
        "demo": "#"
    }
];
